<?php if($this->getCodeStatus()){ ?>
<!-- TruConversion Tracking Code -->
<script type="text/javascript">
    var _tip = _tip || [];
    (function(d,s,id){
        var js, tjs = d.getElementsByTagName(s)[0];
        if(d.getElementById(id)) { return; }
        js = d.createElement(s); js.id = id;
        js.async = true;
        js.src = d.location.protocol + '//<?php echo 'app.trucon.local/ti-js/' . $this->getDomainId() . '/mag10.js'?>';
        tjs.parentNode.insertBefore(js, tjs);
    }(document, 'script', 'ti-js'));
</script>
<!-- End TruConversion Tracking Code -->
<?php } ?>